MF= Makefile

FC= gfortran

FFLAGS= -g 
FFLAGS= -O3 
LFLAGS= $(FFLAGS) 

EXE= main.exe

SRC= \
	main.f90 \
	subr.f90

#
# No need to edit below this line
#

.SUFFIXES:
.SUFFIXES: .f90 .o

OBJ= $(SRC:.f90=.o)
MOD= $(SRC:.f90=.mod)

.f90.o:
	$(FC) $(FFLAGS) -c $<

all: $(EXE)

$(EXE): $(OBJ)
	$(FC) $(FFLAGS) -o $@ $(OBJ) $(LFLAGS)

$(OBJ): $(MF)

main.o: subr.o 

clean:
	rm -f $(OBJ) $(MOD) $(EXE) core
